# Generated by Django 4.2.7 on 2023-11-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Isbn',
            field=models.CharField(default=-9772, max_length=13),
            preserve_default=False,
        ),
    ]
